from langchain_core.prompts import ChatPromptTemplate
from llm import llm

prompt_to_generate_questions = ChatPromptTemplate.from_messages([
    ("system",
        """
        You are a SQL expert.
        Your goal is to generate synthetic and dynamic User Questions and corresponding dynamic SQL queries based on a given data schema.
        
        **Rules:**
        1. Ensure the SQL is syntactically correct for SQLite.
        2. Use the provided Dynamic Fields placeholders (e.g. `<artist_name>`) instead of hardcoded values (e.g. 'AC/DC').
        3. Do not invent new dynamic fields; only use the ones listed below.

        **The "Spotlight" Rule:**
        You will be given a specific **Target Table**.
        Your questions MUST revolve around the metrics and attributes of that specific table.
        * **Good:** If Target is 'Employee', ask "Which Employee generated the most sales?" (Uses joins, but about Employee).
        * **Bad:** If Target is 'Employee', do not ask "Which Track is the longest?" (Irrelevant to Employee).

        **Available Dynamic Fields:**
```
{template_fields}
```
        
        **Few-Shot Examples:**
        
        Example 1: Time-Bound Sales
        {{
            "Q": "How many individual tracks did <artist_name> sell between <start_date> and <end_date>?",
            "A": "SELECT COUNT(il.InvoiceLineId) as total_tracks_sold FROM InvoiceLine il JOIN Track t ON il.TrackId = t.TrackId JOIN Album a ON t.AlbumId = a.AlbumId JOIN Artist art ON a.ArtistId = art.ArtistId JOIN Invoice i ON il.InvoiceId = i.InvoiceId WHERE art.Name = '<artist_name>' AND i.InvoiceDate BETWEEN '<start_date>' AND '<end_date>';"
        }}

        Example 2: Regional Market Analysis
        {{
            "Q": "List all customers in <country_name> who have purchased <genre_name> music.",
            "A": "SELECT DISTINCT c.FirstName, c.LastName, c.Email FROM Customer c JOIN Invoice i ON c.CustomerId = i.CustomerId JOIN InvoiceLine il ON i.InvoiceId = il.InvoiceId JOIN Track t ON il.TrackId = t.TrackId JOIN Genre g ON t.GenreId = g.GenreId WHERE g.Name = '<genre_name>' AND i.BillingCountry = '<country_name>';"
        }}

        Example 3: Employee Revenue
        {{
            "Q": "What is the total revenue generated by sales support agent <employee_last_name>?",
            "A": "SELECT e.FirstName, e.LastName, SUM(i.Total) as total_revenue FROM Employee e JOIN Customer c ON e.EmployeeId = c.SupportRepId JOIN Invoice i ON c.CustomerId = i.CustomerId WHERE e.LastName = '<employee_last_name>';"
        }}
        """
    ),
    ("human",
        """
        **Full Schema (Context):**
        {schema}

        **Target Table (Focus):**
        {target_table}

        **Task:**
        Generate {question_number} distinct questions specifically about the '{target_table}'.
        """
    )
])

def get_generate_questions_chain(QuestionBatchClass):
    # This is where the output is structured to the Pydantic class.
    structured_llm = llm.with_structured_output(QuestionBatchClass)
    # Create final chain
    return prompt_to_generate_questions | structured_llm
